### ISSUE TITLE
reproducing evolutionary indices with example scripts

### ISSUE THREAD

**Issue by AndreaGraf** [OATML/EVE#3]
Hi, 

I am trying to reproduce the results from your publication and evemodel.org. For the PTEN example this works well, but for the other proteins for which there is data in the repo (e.g. P53_HUMAN) the distribution of evolutionary indices is always shifted (or somewhat squashed) to lower values, compared to the distributions shown in the , like in the example below. Do you use the same default parameters and scripts for all example proteins ? And if not which should be tuned/changed from the PTEN example?
 
![histogram_random_samples_next_P53_HUMAN](https://user-images.githubusercontent.com/61273320/148081788-ff39a9fa-cbff-42b0-b65c-81d299d13f71.png)

**Comment by pascalnotin** [comment]
Dear Andrea,
Apologies for the delayed response. Yes, we use the same default parameters for all proteins. Have you been able to reproduce the results since?
Kind regards,
Pascal

**Comment by pascalnotin** [comment]
Closing the issue now but feel free to re-open if needed.
