### ISSUE TITLE
About the trained models and ROC curve

### ISSUE THREAD

**Issue by wliusjtu** [OATML/EVE#4]
Dear authors,

We are recently working on your paper and the released code, and we have the following two issues that we hope you could help us to manage them:

1. training the models for all the protein sequences from scratch is quite time-consuming, we are thus wondering if there are trained models of all the protein sequences along with the released code?
2. you evaluated AUC and ROC in your paper, however, it seems there is no corresponding code in the released one, could you please provide the code?

Many thanks.

**Comment by pascalnotin** [comment]
Dear Wei,
Apologies about the delayed response. Regarding your two questions:
1. We have made available all scores for the proteins we have trained models for at: https://evemodel.org/. You may also download from that website the MSAs we used to train the different models with the training script in the repo (latest version available at: https://github.com/OATML-Markslab/EVE).
2. Whenever we mention AUC in the paper, we always mean Area Under the Receiver Operating Characteristic. We use the default implementation from sklearn.metrics. See for example the performance_helpers.py script under utils (https://github.com/OATML-Markslab/EVE/blob/master/utils/performance_helpers.py#L42).
Kind regards,
Pascal

**Comment by pascalnotin** [comment]
Closing the issue now but feel free to re-open if needed.
